### ISSUE TITLE
Unable to install torndown via pip

### ISSUE THREAD

**Issue by timgabets** [stevepeak/torndown#2]
Hi, seems that the torndown is not available via pip
```
# pip install torndown
Collecting torndown
  Could not find a version that satisfies the requirement torndown (from versions: )
No matching distribution found for torndown
```
is it alive?

**Comment by stevepeak** [comment]
I'm no longer able to maintain this project... sorry :( 
If you, or anyone, would like to take it over I would gladly pass it along.

**Comment by timgabets** [comment]
Yes, I would like to pick it up

**Comment by stevepeak** [comment]
Ok, transferring 👍

**Comment by timgabets** [comment]
Thanks! 
May I also ask you to change the ownership of the torndown package on [PyPi](https://pypi.python.org/pypi/torndown/), and set me as a new package owner?
Thank you.
